# Generated by Django 5.0.8 on 2024-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_create_activity_and_itinerary_item_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("items", models.ManyToManyField(to="planner.itineraryitem")),
            ],
        ),
    ]
