# Generated by Django 5.0.8 on 2024-08-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_create_itinerary_item_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="itineraryitemgroup",
            name="itinerary",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="planner.itinerary",
            ),
            preserve_default=False,
        ),
    ]
