# Generated by Django 5.0.8 on 2024-08-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_associate_itineary_with_itinerary_item_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itineraryitemgroup",
            name="items",
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="planner.itineraryitemgroup",
            ),
            preserve_default=False,
        ),
    ]
