# Generated by Django 5.0.8 on 2024-08-09 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0005_change_itinerary_item_group_to_one_to_many"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "Activity", "verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="itinerary",
            options={"verbose_name": "Itinerary", "verbose_name_plural": "Itineraries"},
        ),
        migrations.AlterModelOptions(
            name="itineraryitem",
            options={
                "verbose_name": "Itinerary Item",
                "verbose_name_plural": "Itinerary Items",
            },
        ),
        migrations.AlterModelOptions(
            name="itineraryitemgroup",
            options={
                "verbose_name": "Itinerary Item Groups",
                "verbose_name_plural": "Itinerary Item Groups",
            },
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itinerary_item",
                to="planner.activity",
            ),
        ),
        migrations.AlterField(
            model_name="itineraryitem",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itinerary_item_group",
                to="planner.itineraryitemgroup",
            ),
        ),
    ]
