# Generated by Django 5.0.8 on 2024-08-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_alter_activity_options_alter_itinerary_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryitem",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="itineraryitemgroup",
            name="itinerary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itinerary",
                to="planner.itinerary",
            ),
        ),
    ]
