# Generated by Django 5.0.8 on 2024-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_activity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="full_description",
            field=models.TextField(blank=True),
        ),
    ]
